version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install JDK 21
          command: |
            sudo apt-get update -y
            sudo apt-get install -y openjdk-21-jdk
            java -version
      - run:
          name: Ensure Docker is running
          command: |
            docker --version
            docker info
            docker ps
      - gradle/with_cache:
          steps:
            - run:
                name: Build and Test
                command: ./gradlew clean build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
          destination: reports

  publish-to-maven:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install JDK 21
          command: |
            sudo apt-get update -y
            sudo apt-get install -y openjdk-21-jdk
            java -version
      - run:
          name: Ensure Docker is running
          command: |
            docker --version
            docker info
            docker ps
      - run:
          name: Set Version Based on Branch
          command: |
            # Determine if this is a main branch build or a feature branch build
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              # For main branch, use a release version with build number
              echo "export VERSION=1.0.${CIRCLE_BUILD_NUM}" >> $BASH_ENV
              echo "export IS_SNAPSHOT=false" >> $BASH_ENV
            else
              # For feature branches, use a SNAPSHOT version
              echo "export VERSION=1.0.0-SNAPSHOT" >> $BASH_ENV
              echo "export IS_SNAPSHOT=true" >> $BASH_ENV
            fi
            source $BASH_ENV
            echo "Using version: ${VERSION} (IS_SNAPSHOT: ${IS_SNAPSHOT})"
      - gradle/with_cache:
          steps:
            - run:
                name: Build with Version
                command: |
                  echo "Using version: ${VERSION}"
                  ./gradlew clean build -Pversion=${VERSION}
            - run:
                name: Publish to Local Maven Repository
                command: |
                  echo "Publishing with version: ${VERSION}"
                  ./gradlew publishToMavenLocal -Pversion=${VERSION}
      - run:
          name: Create and Push Git Tag (Main Branch Only)
          command: |
            # Only create tags for main branch (non-snapshot) builds
            if [ "${IS_SNAPSHOT}" == "false" ]; then
              echo "Creating tag for version: ${VERSION}"
              git config user.email "ci@incept5.com"
              git config user.name "CircleCI"
              
              # Check if tag already exists
              if git rev-parse "${VERSION}" >/dev/null 2>&1; then
                echo "Tag ${VERSION} already exists, skipping tag creation"
              else
                echo "Creating new tag ${VERSION}"
                git tag -a "${VERSION}" -m "Release version ${VERSION}"
                git push origin "${VERSION}"
              fi
            else
              echo "Skipping tag creation for SNAPSHOT version"
            fi
      - run:
          name: Trigger JitPack Build (Main Branch Only)
          command: |
            # Only trigger JitPack for main branch (non-snapshot) builds
            if [ "${IS_SNAPSHOT}" == "false" ]; then
              # Debug information
              echo "Maven repository location: $HOME/.m2/repository"
              echo "Using version: ${VERSION}"
              
              # List all artifacts in the local Maven repository
              echo "All artifacts in Maven repository:"
              find $HOME/.m2/repository/com/github/incept5 -type f -name "*.jar" | sort
              
              if [ ! -f "$HOME/.m2/repository/com/github/incept5/platform-core-lib/${VERSION}/platform-core-lib-${VERSION}.jar" ]; then
                echo "platform-core-lib JAR not found locally at expected path"
                echo "Expected: $HOME/.m2/repository/com/github/incept5/platform-core-lib/${VERSION}/platform-core-lib-${VERSION}.jar"
              
                # Check if the directory exists
                if [ -d "$HOME/.m2/repository/com/github/incept5/platform-core-lib" ]; then
                  echo "Available versions for platform-core-lib:"
                  ls -la "$HOME/.m2/repository/com/github/incept5/platform-core-lib/"
                fi
              
                # Try to find it elsewhere
                echo "Searching for platform-core-lib JAR:"
                find $HOME/.m2/repository -name "platform-core-lib-*.jar" | sort
              
                # Try one more publish with explicit version
                echo "Attempting one more publish with explicit version ${VERSION}"
                ./gradlew clean build publishToMavenLocal -Pversion=${VERSION} --stacktrace
              
                # Check again
                if [ -f "$HOME/.m2/repository/com/github/incept5/platform-core-lib/${VERSION}/platform-core-lib-${VERSION}.jar" ]; then
                  echo "Successfully published platform-core-lib JAR after retry"
                else
                  echo "Failed to publish platform-core-lib JAR after retry"
                  exit 1
                fi
              fi
              
              echo "Artifact verified locally"
              
              # Trigger JitPack build by making a request to the JitPack URL with the version tag
              echo "Triggering JitPack build for version ${VERSION}"
              curl -s "https://jitpack.io/com/github/incept5/platform-core-lib/${VERSION}/platform-core-lib-${VERSION}.pom" || true
              
              echo "JitPack build triggered for version ${VERSION}"
              echo "Library will be available at: https://jitpack.io/#incept5/platform-core-lib/${VERSION}"
              
              # Wait for JitPack to process the build
              echo "Waiting for JitPack to process the build..."
              sleep 180  # Wait time for JitPack to process
              
              # Verify the build status
              JAR_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/platform-core-lib/${VERSION}/platform-core-lib-${VERSION}.jar")
              if [ "$JAR_STATUS" -eq 200 ]; then
                echo "Library successfully published to JitPack!"
              else
                echo "Library not found on JitPack. Status code: $JAR_STATUS"
                echo "Check status at: https://jitpack.io/#incept5/platform-core-lib/${VERSION}"
              fi
              
              # Verify POM availability
              POM_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://jitpack.io/com/github/incept5/platform-core-lib/${VERSION}/platform-core-lib-${VERSION}.pom")
              if [ "$POM_STATUS" -eq 200 ]; then
                echo "POM successfully published to JitPack!"
              else
                echo "POM not found on JitPack. Status code: $POM_STATUS"
              fi
              
              # Final verification
              if [ "$JAR_STATUS" -eq 200 ] && [ "$POM_STATUS" -eq 200 ]; then
                echo "Platform Core Library successfully published to JitPack!"
              else
                echo "WARNING: Library may not be available yet on JitPack."
                echo "This is normal as JitPack may take some time to process the build."
                echo ""
                echo "To use this library in your project:"
                echo "1. Add the JitPack repository to your build file"
                echo "   repositories {"
                echo "     maven { url 'https://jitpack.io' }"
                echo "   }"
                echo ""
                echo "2. Add the dependency"
                echo "   dependencies {"
                echo "     implementation 'com.github.incept5:platform-core-lib:${VERSION}'"
                echo "   }"
                echo ""
              fi
            else
              echo "Skipping JitPack publishing for SNAPSHOT version"
            fi

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-and-test
      - publish-to-maven:
          requires:
            - build-and-test
